apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: notam
spec:
  environments:
    - name: dev
      build:
        from: master
  components:
    - name: main
      src: "./"
      public: true
      ports:
        - name: http
          port: 80
  dnsAppAlias:
    environment: dev
    component: main